//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAssessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bom
    {
        public int C__id { get; set; }
        public Nullable<int> ParentConfigIndex { get; set; }
        public Nullable<int> ChildConfigIndex { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<bool> Excluded { get; set; }
        public Nullable<bool> Suppressed { get; set; }
    }
}
