//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAssessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public int C__id { get; set; }
        public Nullable<int> Id { get; set; }
        public string PartNo { get; set; }
        public string Description { get; set; }
        public string Revision { get; set; }
        public string FilePath { get; set; }
        public string ConfigurationName { get; set; }
        public string BomPartNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsRoot { get; set; }
        public byte[] Preview { get; set; }
    }
}
